spring:
  application:
    name:PhotoAppAPIConfigServer

  cloud:
    config:
      server:
        git:
          uri: https://github.com/DimitarRadev88/photo-app-configuration-repo
          default-label: master
          username: ${github.user}
          password: ${github.password}

  rabbitmq:
    username: user
    password: password

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh

server:
  port: 8088

